export enum AppRoutes {
  Home = '/',
  Services = '/products/our-service',
  Programs = '/products/our-programs',
  About = '/community/about',
  Contact = '/community/contact',
  Terms = '/community/terms',
  Privacy = '/community/privacy',
  Blog = '/blog',
  SignIn = '/auth/sign-in',
  SignUp = '/auth/sign-up',
  SignOut = '/auth/sign-out',
  ForgotPassword = '/auth/forgot/password',

  AdminManageDashboard = '/admin/dashboard',
  AdminManageServices = '/admin/manage-services',
  AdminManageTravels = '/admin/manage-travels',
  AdminManageOrders = '/admin/manage-orders',
  AdminManageCategories = '/admin/manage-categories',
  AdminManageBlogs = '/admin/manage-blogs',
  AdminManageComments = '/admin/manage-comments',
  AdminManageSettings = '/admin/manage-settings',
  AdminManagePages = '/admin/manage-pages',
  AdminManageProfile = '/admin/manage-profile',
}
