name: Build Containers for Prod & Push to Dockerhub
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

env:
  API_TEST_TAG: amineyagoub/travel-api:test
  UI_TEST_TAG: amineyagoub/travel-frontend:test
  API_LATEST_TAG: amineyagoub/travel-api:latest
  UI_LATEST_TAG: amineyagoub/travel-frontend:latest

jobs:
  build-and-deploy-API:
    name: Build and Deploy API
    runs-on: ubuntu-latest
    services:
      percona:
        image: percona
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: pass123
          MYSQL_DATABASE: travel
        ports:
          - 3306:3306
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/gateway/Dockerfile
          load: true
          tags: ${{ env.API_TEST_TAG }}

      - name: Test API container
        run: |
          docker run -itd --network=${{ job.services.percona.network }} \
              -e DATABASE_URL=mysql://user:pass123@percona:3306/travel \
              -e WAIT_HOSTS=percona:3306 \
              --rm ${{ env.API_TEST_TAG }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/gateway/Dockerfile
          push: true
          tags: ${{ env.API_LATEST_TAG }}
  #build-and-deploy-frontend:
  #  name: Build and Deploy frontend
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v3
  #    - name: Set up QEMU
  #      uses: docker/setup-qemu-action@v2
  #    - name: Set up Docker Buildx
  #      uses: docker/setup-buildx-action@v2
  #    - name: Login to Docker Hub
  #      uses: docker/login-action@v2
  #      with:
  #        username: ${{ secrets.DOCKER_USERNAME }}
  #        password: ${{ secrets.DOCKER_PASSWORD }}
  #    - name: Build and push to Docker
  #      uses: docker/build-push-action@v3
  #      with:
  #        context: .
  #        file: apps/ui/Dockerfile
  #        push: true
  #        tags: ${{ env.UI_LATEST_TAG }}
